spring:
  application:
    name: KozakBurgerShop
  datasource:
    url: jdbc:postgresql://localhost:5432/KozakTest2
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
server:
  servlet:
    context-path: /api

key:
  access: wwm4cDfkCrzh5QRu5/xGR6n4xqsaKVGFmI/Cyk6sp2A=
  refresh: nxGGtCBgMnAmIweXFTkaU1dPl0IsfitxRnmyxasDQlY=

