spring:
  application:
    name: KozakBurgerShop
  datasource:
    url: jdbc:postgresql://localhost:5432/KozakTest2
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  server:
    servlet:
      context-path: /api

